### ISSUE TITLE
We are not seeing sleep data

### ISSUE THREAD

**Issue by jeydude1** [BIDMCDigitalPsychiatry/LAMP-platform#119]
We are using a thirdparty wearable device that syncs data with Apple Health app. I see Sleep Data in Apple Health app. But for some reason I am not getting sleep data in mindLAMP database.

Here are the list of sensors data we are getting so far
•	lamp.accelerometer
•	lamp.accelerometer.motion
•	lamp.analytics
•	lamp.bluetooth
•	lamp.calls
•	lamp.distance
•	lamp.gps
•	lamp.gyroscope
•	lamp.heart_rate
•	lamp.magnetometer
•	lamp.screen_state
•	lamp.steps
•	lamp.wifi

Here is the URL I have tried
https://< APIHOSTNAME >/participant/<PARTICIPANTID>/sensor_event?origin=lamp.sleep
got empty data:
Response:
{
"data": [],
}

Tried the python code
events = LAMP.SensorEvent.all_by_participant(participantId, origin='lamp.sleep')['data'][:5]

No data

Is there any reason why we are not getting sleep data but we are getting rest of the wearable's sensor data?

**Comment by jeydude1** [comment]
I looked at your iOS code in the git repository, looks like you guys are not storing sleep data, please verify. Thanks!

**Comment by jijopulikkottil** [comment]
Hi @jeydude1 The source code to collect sleep data reside in LAMP-Swift repository. Code seems to be fine. I will update you after verification. Thanks

**Comment by jijopulikkottil** [comment]
Hi @jeydude1 Yes, not getting sleep data when test with AppStore build. But we are getting sleep data with latest test flight build. @avaidyam

**Comment by jeydude1** [comment]
Thanks for testing and confirming @jijopulikkottil. Good to know we will be getting sleep data in the new releases. Appreciate much!

**Comment by jeydude1** [comment]
@jijopulikkottil, is there any way to test the sleep data collection with test flight build, or do we need to wait until official release with Android? If you have link for test flight build for us, please share. Thanks!

**Comment by avaidyam** [comment]
@jeydude1 Please see our docs at https://docs.lamp.digital → downloading the app. At the bottom are instructions for beta releases.

**Comment by jeydude1** [comment]
@avaidyam, installed the test flight version of the app from docs site - https://docs.lamp.digital/793ab1170c064940b772c6a5989258e5

Looks like test flight version does not synchronize the sensor data., tested for few hours no sensors data  :(

Please let us know when you will be releasing next version of iOS app in apple store, so we can try it. Thanks!

**Comment by avaidyam** [comment]
You actually will need to use the dashboard to enable the specific sensors (using the new patient configuration screen) you want to collect data from before the new beta build will upload that data.

**Comment by jeydude1** [comment]
Thanks @avaidyam, I have added few sensors to the patient profile screen, I am not seeing anything on sensor specification, Looks OK to you?
![image](https://user-images.githubusercontent.com/205644/109184786-f073a100-7754-11eb-8564-15e11cbe10f9.png)

**Comment by jeydude1** [comment]
I believe I got it working to get health app data with beta version of iOS app, I have entered the sensor_spec from here - https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/8#issuecomment-770976348

Here is the sensors data I have updated to collect for a patient profile
![image](https://user-images.githubusercontent.com/205644/109233812-241fec80-7790-11eb-8719-444673e5cbaf.png)


Here is the data in the couchdb sensor_spec database
```
{
      "id": "432c05e5f2e9c2a32c34fb44f7b73eaf",
      "key": "432c05e5f2e9c2a32c34fb44f7b73eaf",
      "value": {
        "rev": "2-3fbf413b51f5d11070edf9595f139acb"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b73eaf",
        "_rev": "2-3fbf413b51f5d11070edf9595f139acb",
        "id": "lamp.accelerometer.motion",
        "type": "object",
        "properties": {
          "tilt": {
            "type": "object",
            "properties": {
              "roll": {
                "type": "number"
              },
              "pitch": {
                "type": "number"
              },
              "yaw": {
                "type": "number"
              }
            }
          },
          "rotation": {
            "type": "object",
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              },
              "z": {
                "type": "number"
              }
            }
          },
          "gravity": {
            "type": "object",
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              },
              "z": {
                "type": "number"
              }
            }
          },
          "user_accel": {
            "type": "object",
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              },
              "z": {
                "type": "number"
              }
            }
          },
          "magnetic_field": {
            "type": "object",
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              },
              "z": {
                "type": "number"
              },
              "calibration_accuracy": {
                "type": "number"
              }
            }
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b75d33",
      "key": "432c05e5f2e9c2a32c34fb44f7b75d33",
      "value": {
        "rev": "1-255ce465601b3e632d2253bfbfa42792"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b75d33",
        "_rev": "1-255ce465601b3e632d2253bfbfa42792",
        "id": "lamp.analytics",
        "type": "object",
        "properties": {
          "event_name": {
            "type": "string"
          },
          "event_payload": {
            "type": "object",
            "additionalProperties": true
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b7623b",
      "key": "432c05e5f2e9c2a32c34fb44f7b7623b",
      "value": {
        "rev": "1-7b4caf5dfd9856566a9477db165badc5"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b7623b",
        "_rev": "1-7b4caf5dfd9856566a9477db165badc5",
        "id": "lamp.blood_pressure",
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "units": {
            "type": "string"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b76f41",
      "key": "432c05e5f2e9c2a32c34fb44f7b76f41",
      "value": {
        "rev": "1-0032c9bac846ba6cfb326d226e944d25"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b76f41",
        "_rev": "1-0032c9bac846ba6cfb326d226e944d25",
        "id": "lamp.bluetooth",
        "type": "object",
        "properties": {
          "device__id": {
            "type": "string"
          },
          "frequency": {
            "type": "number"
          },
          "rssi": {
            "type": "number"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b77ce8",
      "key": "432c05e5f2e9c2a32c34fb44f7b77ce8",
      "value": {
        "rev": "1-6fc8374cfa845ec1db1ccbb2e8be66c3"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b77ce8",
        "_rev": "1-6fc8374cfa845ec1db1ccbb2e8be66c3",
        "id": "lamp.calls",
        "type": "object",
        "properties": {
          "phone_number": {
            "type": "string"
          },
          "duration": {
            "type": "number"
          },
          "call_type": {
            "type": "string",
            "enum": [
              "incoming",
              "outgoing",
              "missed",
              "busy"
            ]
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b78a19",
      "key": "432c05e5f2e9c2a32c34fb44f7b78a19",
      "value": {
        "rev": "1-6a53db555d96e75b36dc37bd99486abb"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b78a19",
        "_rev": "1-6a53db555d96e75b36dc37bd99486abb",
        "id": "lamp.device_state",
        "type": "object",
        "properties": {
          "battery_level": {
            "type": "number"
          },
          "event_type": {
            "type": "string",
            "enum": [
              "locked",
              "unlocked",
              "plugged",
              "unplugged",
              "screen_on",
              "screen_off"
            ]
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b79b3d",
      "key": "432c05e5f2e9c2a32c34fb44f7b79b3d",
      "value": {
        "rev": "1-29fce1b29a969b6adf1f5b3f3a7fda19"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b79b3d",
        "_rev": "1-29fce1b29a969b6adf1f5b3f3a7fda19",
        "id": "lamp.distance",
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "units": {
            "type": "string"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b7b00c",
      "key": "432c05e5f2e9c2a32c34fb44f7b7b00c",
      "value": {
        "rev": "1-2795980e1030ee7485eaa90468217489"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b7b00c",
        "_rev": "1-2795980e1030ee7485eaa90468217489",
        "id": "lamp.flights",
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "units": {
            "type": "string"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b7c5cb",
      "key": "432c05e5f2e9c2a32c34fb44f7b7c5cb",
      "value": {
        "rev": "1-b1aaacc6505155dc9559c90387e883b2"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b7c5cb",
        "_rev": "1-b1aaacc6505155dc9559c90387e883b2",
        "id": "lamp.gps",
        "type": "object",
        "description": "The location sensor records the device's current GPS coordinates. Depending on the device operating system and device battery level, the source of the data from this sensor may alternate between GPS antennae (high accuracy), cellular tower triangulation (moderate accuracy), WiFi triangulation (poor accuracy), or a combination of these.",
        "properties": {
          "latitude": {
            "type": "number",
            "description": "The coordinate's latitude in degrees."
          },
          "longitude": {
            "type": "number",
            "description": "The coordinate's longitude in degrees."
          },
          "altitude": {
            "type": "number",
            "description": "The coordinate's altitude in meters, relative to sea level. A value of zero implies that the altitude of the coordinate could not be determined."
          },
          "accuracy": {
            "type": "number",
            "description": "The coordinate's estimated accuracy representing the radius of a circle formed around the reported latitude/longitude pair, for which there is AT LEAST a 68% probability that the true coordinate is contained within (the 'Circular Error Probable'). A value of zero implies that the accuracy of the coordinate could not be determined."
          },
          "bearing": {
            "type": "number",
            "description": "(Currently unsupported.) The bearing is the horizontal direction of travel, in degrees, estimated by the GPS satellites to the device when requesting coordinates, thus this value is different than if calculated from accelerometer and magnetic field measurements."
          },
          "speed": {
            "type": "number",
            "description": "(Currently unsupported.) The current estimated speed of travel over ground, in meters/second."
          }
        },
        "required": [
          "latitude",
          "longitude",
          "altitude",
          "accuracy"
        ],
        "additionalProperties": false
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b7d832",
      "key": "432c05e5f2e9c2a32c34fb44f7b7d832",
      "value": {
        "rev": "1-603858323d5c64d25c1169ef9254d1db"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b7d832",
        "_rev": "1-603858323d5c64d25c1169ef9254d1db",
        "id": "lamp.gps.contextual",
        "type": "object",
        "properties": {
          "latitude": {
            "type": "number"
          },
          "longitude": {
            "type": "number"
          },
          "accuracy": {
            "type": "number"
          },
          "social_context": {
            "type": "string",
            "enum": [
              "home",
              "school",
              "work",
              "hospital",
              "outs_ide",
              "transit"
            ]
          },
          "location_context": {
            "type": "string",
            "enum": [
              "alone",
              "friends",
              "family",
              "crowd"
            ]
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b7f2dd",
      "key": "432c05e5f2e9c2a32c34fb44f7b7f2dd",
      "value": {
        "rev": "1-815979a06b7f436084dbd2b14ccd3ddc"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b7f2dd",
        "_rev": "1-815979a06b7f436084dbd2b14ccd3ddc",
        "id": "lamp.gyroscope",
        "type": "object",
        "properties": {
          "x": {
            "type": "number"
          },
          "y": {
            "type": "number"
          },
          "z": {
            "type": "number"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b80825",
      "key": "432c05e5f2e9c2a32c34fb44f7b80825",
      "value": {
        "rev": "1-5b1ae38783d3baa7345b3125391b21d9"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b80825",
        "_rev": "1-5b1ae38783d3baa7345b3125391b21d9",
        "id": "lamp.heart_rate",
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "units": {
            "type": "string"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b81dcb",
      "key": "432c05e5f2e9c2a32c34fb44f7b81dcb",
      "value": {
        "rev": "1-8e2719af0f60bde6f4624cc000d919ae"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b81dcb",
        "_rev": "1-8e2719af0f60bde6f4624cc000d919ae",
        "id": "lamp.height",
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "units": {
            "type": "string"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b82d05",
      "key": "432c05e5f2e9c2a32c34fb44f7b82d05",
      "value": {
        "rev": "1-a5c8beae508126e47a584b9fd81be1b6"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b82d05",
        "_rev": "1-a5c8beae508126e47a584b9fd81be1b6",
        "id": "lamp.magnetometer",
        "type": "object",
        "properties": {
          "x": {
            "type": "number"
          },
          "y": {
            "type": "number"
          },
          "z": {
            "type": "number"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b84099",
      "key": "432c05e5f2e9c2a32c34fb44f7b84099",
      "value": {
        "rev": "1-9ce7b347d324957b4151c3e55019fbb8"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b84099",
        "_rev": "1-9ce7b347d324957b4151c3e55019fbb8",
        "id": "lamp.respiratory_rate",
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "units": {
            "type": "string"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b85994",
      "key": "432c05e5f2e9c2a32c34fb44f7b85994",
      "value": {
        "rev": "1-3038d22315fb27f56a9f63928f46e2aa"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b85994",
        "_rev": "1-3038d22315fb27f56a9f63928f46e2aa",
        "id": "lamp.segment",
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "units": {
            "type": "string"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b8679a",
      "key": "432c05e5f2e9c2a32c34fb44f7b8679a",
      "value": {
        "rev": "1-fd3a2129c342077e6add81764e358ec7"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b8679a",
        "_rev": "1-fd3a2129c342077e6add81764e358ec7",
        "id": "lamp.sleep",
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "units": {
            "type": "string"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b87149",
      "key": "432c05e5f2e9c2a32c34fb44f7b87149",
      "value": {
        "rev": "1-393c7b2fef6ebb05ceab028ef5e4b54f"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b87149",
        "_rev": "1-393c7b2fef6ebb05ceab028ef5e4b54f",
        "id": "lamp.sms",
        "type": "object",
        "properties": {
          "phone_number": {
            "type": "string"
          },
          "length": {
            "type": "integer",
            "format": "int64"
          },
          "sms_type": {
            "type": "string",
            "enum": [
              "sent",
              "received"
            ]
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b87dfd",
      "key": "432c05e5f2e9c2a32c34fb44f7b87dfd",
      "value": {
        "rev": "1-7c6de587694e6552a5f34f3196a407ec"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b87dfd",
        "_rev": "1-7c6de587694e6552a5f34f3196a407ec",
        "id": "lamp.steps",
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "units": {
            "type": "string"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b899cf",
      "key": "432c05e5f2e9c2a32c34fb44f7b899cf",
      "value": {
        "rev": "1-99cb3abd95bc3958ee74a1a7dee0bbba"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b899cf",
        "_rev": "1-99cb3abd95bc3958ee74a1a7dee0bbba",
        "id": "lamp.weight",
        "type": "object",
        "properties": {
          "value": {
            "type": "number"
          },
          "units": {
            "type": "string"
          }
        }
      }
    },
    {
      "id": "432c05e5f2e9c2a32c34fb44f7b8ae82",
      "key": "432c05e5f2e9c2a32c34fb44f7b8ae82",
      "value": {
        "rev": "1-1bc00c7d41bc91b89695d55993e96229"
      },
      "doc": {
        "_id": "432c05e5f2e9c2a32c34fb44f7b8ae82",
        "_rev": "1-1bc00c7d41bc91b89695d55993e96229",
        "id": "lamp.wifi",
        "type": "object",
        "properties": {
          "device__id": {
            "type": "string"
          },
          "frequency": {
            "type": "number"
          },
          "rssi": {
            "type": "number"
          }
        }
      }
    },
    {
      "id": "44c2032bce9f9aa6d10d15be64540f04",
      "key": "44c2032bce9f9aa6d10d15be64540f04",
      "value": {
        "rev": "1-2dc5c180e5fd1a93b98bef6766991c24"
      },
      "doc": {
        "_id": "44c2032bce9f9aa6d10d15be64540f04",
        "_rev": "1-2dc5c180e5fd1a93b98bef6766991c24",
        "id": "lamp.accelerometer",
        "type": "object",
        "properties": {
          "x": {
            "type": "number"
          },
          "y": {
            "type": "number"
          },
          "z": {
            "type": "number"
          },
          "accuracy": {
            "type": "number"
          }
        }
      }
    }
```

**Comment by jeydude1** [comment]
@avaidyam please verify my sensor_spec database data, may be I may not have latest info, please share your sensor_spec if you can. Thanks!

**Comment by avaidyam** [comment]
@jeydude1 That looks about right for testing purposes. That set is not quite final just yet, but we will provide the proper upgrade path when we make this release available to others.

**Comment by jijopulikkottil** [comment]
[sensorspec.txt](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6049834/sensorspec.txt)
please try this.

**Comment by kkadapa** [comment]
> Thanks @avaidyam, I have added few sensors to the patient profile screen, I am not seeing anything on sensor specification, Looks OK to you?
> ![image](https://user-images.githubusercontent.com/205644/109184786-f073a100-7754-11eb-8564-15e11cbe10f9.png)
> 
> Once I installed test flight version, In the Health app, Apps Allowed to read data for Sleep, Steps, Heart Rate etc does not have mindLAMP app name listed there. How will Health app will share data to mindLAMP then?

Hi @jeydude1 

> Thanks @avaidyam, I have added few sensors to the patient profile screen, I am not seeing anything on sensor specification, Looks OK to you?
> ![image](https://user-images.githubusercontent.com/205644/109184786-f073a100-7754-11eb-8564-15e11cbe10f9.png)
> 
> Once I installed test flight version, In the Health app, Apps Allowed to read data for Sleep, Steps, Heart Rate etc does not have mindLAMP app name listed there. How will Health app will share data to mindLAMP then?

Hi @jeydude1 Could you kindly help us understand how you've resolved this dropdown? (I am unable to type anything) Were you able to see the steps data on the mobile app after fixing this?

**Comment by jeydude1** [comment]
@kkadapa I have added the above [sensor_spec ](https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/files/6049834/sensorspec.txt) data into into couchdb sensor_spec database manually. Until you add the sensor_spec data, the dropdown list will be empty.

**Comment by kkadapa** [comment]
Thanks @jeydude1 When I tried to copy sensor_spec into couchdb it's showing JSON Formatting errors. Were you able to see other sensor data such as Steps etc?

**Comment by jeydude1** [comment]
I have added one by one :), dont know easy way to populate into couchdb.

Example to add steps copy below into sensor_spec database

{
 "id": "lamp.steps",
 "key": "lamp.steps",
 "value": {
  "rev": "4-d13ce0a73fa151427853586c546e3479"
 },
 "doc": {
  "_id": "lamp.steps",
  "_rev": "4-d13ce0a73fa151427853586c546e3479",
  "type": "object",
  "properties": {
   "value": {
    "type": "number"
   },
   "distance": {
    "type": "number"
   },
   "floors_ascended": {
    "type": "number"
   },
   "floors_descended": {
    "type": "number"
   },
   "pace": {
    "type": "number"
   },
   "cadence": {
    "type": "number"
   },
   "active_pace": {
    "type": "number"
   },
   "calories": {
    "type": "number"
   }
  },
  "description": "",
  "required": {},
  "additionalProperties": false
 }
}

**Comment by kkadapa** [comment]
Thanks @jeydude1 I was only able to see Steps but after I click ADD button the progress indicator goes on an infinite loop 
![image](https://user-images.githubusercontent.com/6679852/109355212-e59c3780-784c-11eb-8f74-a0cc61bcdc88.png) 
![image](https://user-images.githubusercontent.com/6679852/109355368-1b412080-784d-11eb-8063-58c11bb33dcf.png)

**Comment by jeydude1** [comment]
Try refreshing the screen. Verify sensor database does not have newly added steps if does not have add again.

**Comment by kkadapa** [comment]
I refreshed the screen but with no luck, it's going into an infinite loop. I verified and there are no added steps in the Sensor database.

**Comment by jeydude1** [comment]
Sorry Karthik I did not have infinite loop issue. Any error on the API Server or Couch DB?

**Comment by avaidyam** [comment]
> I have added one by one :), don't know easy way to populate into couchdb.

@jeydude1 I believe you're able to use a curl request to the CouchDB instance at the `_bulk_docs` endpoint for the `sensor_spec` database, but figuring that out might take some extra effort. 

When the next backend staging release is ready it'll include an automated upgrade that must be manually executed. This is because all studies need to be re-configured to add sensors, otherwise the apps will stop reporting any passive data. 

@kkadapa If you're not testing out the staging apps you shouldn't need to follow this process. Please make sure you're using an Apple Watch Series 4 and watchOS 7 or higher. Sleep tracking does **NOT** happen by default out of the box on iOS and watchOS 6 or below. You may need to install an app like NapBot and configure that first.

**Comment by jeydude1** [comment]
@avaidyam , please let us know when can we try this sleep data feature either in beta version/production version. Thanks!

**Comment by avaidyam** [comment]
@jeydude1 Have you made sure to use an Apple Watch running watchOS 7? If so it should work on the latest beta.

**Comment by jeydude1** [comment]
@avaidyam, just wanted to confirm, Sleep data works only with Apple Watches?  Not all the study participants are going to have Apple Watches. Some of them are going to use third-party wearables. If we see sleep data in Apple Health App, does mindLAMP app get the sleep data from there?

**Comment by avaidyam** [comment]
@jeydude1 Sleep data on iOS devices requires either a compatible iOS or Apple Watch app **OR** watchOS 7 installed which has sleep tracking built-in. The latest beta of the iOS app should retrieve the third-party app sleep data and correctly tag it with which app the data came from. @jijopulikkottil can you confirm this behavior?

**Comment by jeydude** [comment]
Here are the screenshots to confirm I am using latest beta version of mindLAMP,  Health app permissions,  Sleep data in Health app, my sensor_spec setup, and no sleep data in couchdb. Please let me know what am I missing. Thanks!

mindLAMP beta app 
![IMG_1645](https://user-images.githubusercontent.com/841011/112652849-dc869200-8e1b-11eb-9716-fa0f19026381.PNG)
![IMG_1647](https://user-images.githubusercontent.com/841011/112652870-e01a1900-8e1b-11eb-9b77-a7454ef8e2c8.PNG)
![IMG_1646](https://user-images.githubusercontent.com/841011/112652892-e4decd00-8e1b-11eb-82a4-66b10f541ef6.PNG)

Health app permissions
![IMG_1648](https://user-images.githubusercontent.com/841011/112653017-06d84f80-8e1c-11eb-963f-37700bcc806c.PNG)
![IMG_1649](https://user-images.githubusercontent.com/841011/112653036-0b9d0380-8e1c-11eb-8514-f4ccb35c7acd.PNG)

Third-party app sleep data
![IMG_1642](https://user-images.githubusercontent.com/841011/112652761-c082f080-8e1b-11eb-9d23-c5245a3bf4ec.PNG)

Health app Sleep data
![IMG_1643](https://user-images.githubusercontent.com/841011/112653079-148dd500-8e1c-11eb-9be4-6cfd397e869f.PNG)
![IMG_1644](https://user-images.githubusercontent.com/841011/112653091-1788c580-8e1c-11eb-80af-8c896901b3dc.PNG)

CouchDB setup for sensor_spec data because I am using beta app
![CouchDB_Setup1](https://user-images.githubusercontent.com/841011/112653157-253e4b00-8e1c-11eb-9dfb-4cadb262c9c2.png)
![CouchDB_Setup2](https://user-images.githubusercontent.com/841011/112653166-27a0a500-8e1c-11eb-844c-08c12e43ca0f.png)

CouchDB Sleep data lookup
![Sleep_APICall_Response](https://user-images.githubusercontent.com/841011/112653355-53bc2600-8e1c-11eb-97cd-dbb3e4ca94d3.png)

**Comment by jijopulikkottil** [comment]
@avaidyam , Could you make available the latest build in test flight. I think build 241 is bit old. We have fixed `lamp.sleep` data with this task https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/issues/127

**Comment by avaidyam** [comment]
@jeydude This build should now be available in TestFlight - please give it a shot and report back if it's working! Thanks.

**Comment by jeydude** [comment]
@avaidyam / @jijopulikkottil , last few days I am using mindLAMP 2 test flight version 2021.1.21(257), still not getting any sleep data to CouchDB.

For steps, I see source of sensors but still no sleep data
```
  {
"timestamp": 1617194700000,
"sensor": "lamp.steps",
"data": {
"value": 4135,
"unit": "count",
"source": "com.ido.veryfit"
}
},
  {
"timestamp": 1617194700000,
"sensor": "lamp.steps",
"data": {
"value": 2364,
"unit": "count",
"source": "com.apple.health.0B7AD53A-51E3-4BE2-9C9A-30B9052E7848"
}
}
```

**Comment by jijopulikkottil** [comment]
@jeydude we will update here after checking.

**Comment by jijopulikkottil** [comment]
Hi @jeydude , In iPhone, could you go to 'Health' app and add some sleep data manually (remember that the start time should not be a past time, and the phone battery should not be in low power mode). And after 30 minutes, could you check by calling the API with basic authentication. 
I got sleep data when tried the same. please comment after checking.

**Comment by jeydude** [comment]
Hi @jijopulikkottil, I see sleep data in couchdb if I enter future sleep time manually through Apple Health app, Sleep --> "Add Data" feature. But not sure this will happen during our study. Because 

1. Some of the wearables will not be able auto sync the sleep data to the Apple Health app. 
2. Study participant (wearable user) might have to sync sensor data once they are up from the bed for the previous day (if auto sync did not happen)
3. Study participant will not be able to enter future sleep time in Health app before they go to bed. 
 
Please advice on getting sleep data from wearables. Thanks!

**Comment by avaidyam** [comment]
@jeydude It sounds like then this is an issue with the wearable and the wearable app. If it can't sync with Apple Health it is not something we can resolve on our end. You will need to contact support for the wearable device itself.

**Comment by jeydude** [comment]
@avaidyam even if auto sync happens not sure we will be able to get the actual sleep data based on how @jijopulikkottil described, @jijopulikkottil please let me know. Thanks!

**Comment by jeydude** [comment]
@jijopulikkottil I got my yesterday's sleep data into CouchDB, I will test it for few more days. 

Task I am following to get my sleep data: Once I getup from bed, I open my VeryFitPro/Apple Health app and wait for few seconds to see my sleep data and open mindLAMP app and keep all the apps up in the iPhone. 

Please let me know best practice. Thanks!

**Comment by jijopulikkottil** [comment]
@jeydude Yes,  if auto sync happens, we will be able to get entire sleep data for the previous day. 
"I will test it for few more days." - ok
"...how I am getting sleep data now with beta version.." - we will test it - app should sync automatically without adding manual entry.

**Comment by jeydude** [comment]
@jijopulikkottil , we are getting sleep data from iOS testflight version. Looking forward to see this feature in production apple store version of mindLAMP app.

One last question, currently I have all the sensors listed in the sensor_spec. Do I need to do this in future production version?

**Comment by avaidyam** [comment]
Yes you will need the SensorSpecs in production too.

**Comment by jijopulikkottil** [comment]
In latest build, we have done some improvement in collecting sleep data.
