### ISSUE TITLE
Issues in Try It - Demo

### ISSUE THREAD

**Issue by divyav2020** [BIDMCDigitalPsychiatry/LAMP-platform#681]
1. Try It - Open researcher - open Profile settings -Added a game (eg: jewel). then edited and saved. Then scheduled. Then opened the edit screen and tried to edit/duplicate. Edit and duplicate buttons are in disabled mode

 2.  Try It - Open researcher - open Profile settings -Opened a breathe game and saved. Then scheduled. Then opened edit screen again. But shows progress image only.
 
3. Try It - Open researcher - Open Profile settings - Opened Scratch game and saved. Then scheduled. Then opened edit screen again. . Application crashes

**Comment by sarithapillai8** [comment]
2 & 3 issues are fixed. First one needs to be checked in detail. We will check and update.

**Comment by michaelmenon** [comment]
It is already in staging please test.

**Comment by carlan1** [comment]
Fix is in staging.

**Comment by michaelmenon** [comment]
As Saritha mentioned #2 & #3 issue is fixed. #1 one needs to be checked in detail. Team will update on that asap.

**Comment by sarithapillai8** [comment]
>1.Try It - Open researcher - open Profile settings -Added a game (eg: jewel). then edited and saved. Then scheduled. Then opened the edit screen and tried to edit/duplicate. Edit and duplicate buttons are in disabled mode

This is not fixed. The reason for this bug is that we are not having full properties in demo_db file for all activities. Could you please let me know the priority for this? #2 and #3 are ready for testing.

**Comment by carlan1** [comment]
We can keep low priority for now.

**Comment by michaelmenon** [comment]
Team is working on #1 and will update on this with an ETA.
