### ISSUE TITLE
New Game: Symbol-Digit Substitution Task

### ISSUE THREAD

**Issue by carlan1** [BIDMCDigitalPsychiatry/LAMP-platform#771]
We have requested a new game be developed to be made available on mindLAMP.

Please see the following as a guide: https://cognitionlab.com/project/symbol-digit-substitution-task/#:~:text=The%20Digit%20Symbol%20Substitution%20Task,which%20corresponds%20to%20the%20digit.

Some notes:
- To adapt this task to a mobile device, 9 digits (1-9) should appear as selectable buttons on the bottom of the screen
- The symbol should appear until the participant selects a digit (1-9)
- The configuration options should match those listed on the site

Each symbol that appears on the screen should be encoded as a temporal_slice.
- duration: Symbol number (1, 2, 3 ...etc)
- level: None (There will be no level progression at this time)
- type: The correct symbol that should have been pressed (as a digit from 1-9)
- value: True/False (whether the participant was correct or incorrect)

**Comment by ZCOEngineer** [comment]
@carlan1 acknowledge receipt of this ticket, we shall review and add ETA

**Comment by sarithapillai8** [comment]
We are clear with the requirement. If we need any clarification, we can comment here.

**Comment by sarithapillai8** [comment]
>Each symbol that appears on the screen should be encoded as a temporal_slice.

duration: Symbol number (1, 2, 3 ...etc)
level: None (There will be no level progression at this time)
type: The correct symbol that should have been pressed (as a digit from 1-9)
value: True/False (whether the participant was correct or incorrect)

What is required for the duration parameter? For other games, we are storing the time in milliseconds between the last click and the current click. So please confirm.

**Comment by sarithapillai8** [comment]
@carlan1 We can do like that

**Comment by sarithapillai8** [comment]
@carlan1 Please see the status of the game. Please review : 

https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/63710347/716dc2c4-07cf-493a-94bf-bcaddee9027e

**Comment by sarithapillai8** [comment]
@carlan1 Could you suggest what should be shown in this game's portal graph? Do we need to calculate any score? If score calculation is required, what should be the formula?

**Comment by sarithapillai8** [comment]
@carlan1 Game is updated and working fine in staging. The graph now showing is confusing. So please suggest how to show the values in detailed graph view.

**Comment by carlan1** [comment]
Looks great so far. Very good work. However, we have decided to make some modifications:
1. Instead of a typed response, could you change it to clickable buttons? The top row should be a key/map, the middle should be a prompt showing the symbol that needs to be mapped, and the bottom row should be selectable buttons
2. The selectable buttons (bottom row) should be 1, 2, 3, 4.. etc (not a-z)
3. Could you change the symbol prompts to greek letters? 

For example, the user is prompted with the image of psi. They look at the top row and see psi is mapped to "3". Then they select "3" from the bottom row.

**Comment by sarithapillai8** [comment]
@carlan1 Additionally, please make the scoring in the portal reflect the number of correct responses per minute as the y-axis (this is subject to change depending on future user reviews/feedback)

Could you also suggest what to be shown for detailed graph when switching the view?

**Comment by carlan1** [comment]
Are you able to show a table that includes:
- Number of symbols
- Number of correct responses
- Number of incorrect responses
- Average response time (correct)
- Average response time (incorrect)
We do not need a graph for each response (as is in the current representation)

**Comment by sarithapillai8** [comment]
@carlan1 

>We do not need a graph for each response (as is in the current representation)

Do you want to keep the current graph for each response and show the above values separately in a different table? Or do you want to show a different representation for this game like DBT?

**Comment by carlan1** [comment]
A single graph with x-axis = date and y-axis = average correct responses per minute would be best. Right now, each symbol has its own graph, which is far too many

**Comment by sarithapillai8** [comment]
@carlan1 So do you want to add a table along with current graph or the current representation is enough for now?

**Comment by carlan1** [comment]
The first graph (before clicking "switch views") is good.

The second graphs (after clicking "switch views") are not necessary

**Comment by sarithapillai8** [comment]
@carlan1 'Updated the changes in staging. Please review.

**Comment by evinkalengaden** [comment]
@carlan1 We have tested the new changes, And updated in the dashboard staging.

**Comment by sarithapillai8** [comment]
@carlan1 We missed the configuration part. We can update it and let you know.

**Comment by sarithapillai8** [comment]
Whether to show mapping table (before, during, or not at all)
For this change, we have added a start button only in the case of the value 'before'. Once the start button is clicked, the mapping table will be hidden and the game will start.

**Comment by carlan1** [comment]
Okay sure. Could you add the start button in all cases then?

Also please add a prompt that explains how the mapping will go away (in the go away case)

**Comment by sarithapillai8** [comment]
@ertjlane We can add start button in all cases.
Can you suggest the text to be shown in the prompt?

**Comment by carlan1** [comment]
We can simply have instructions for the game:

"In this game, you will be shown a symbol in the middle of your screen, represented by a greek letter. This symbol will correspond to a numerical digit. There is a symbol-mapping legend in the top row of your screen. Use the legend to identify the digit which corresponds to your symbol. Then, press the button at the bottom of the screen which contains this digit. After you select the correct button, you will move on to a new symbol. Try to get as many symbols as you can."

However, in the case where the key goes away, add the following: "Try to memorize the key. Once you press start, it will go away!"

**Comment by evinkalengaden** [comment]
@carlan1 We have tested the new changes, And updated in the dashboard staging.

**Comment by carlan1** [comment]
It does not seem to be working properly after the update. There is no symbol, no mapping, and I cannot see how many seconds remain. 

<img width="1364" alt="Screen Shot 2023-11-16 at 2 54 47 PM" src="https://github.com/BIDMCDigitalPsychiatry/LAMP-platform/assets/103652751/7496086d-375d-4e5b-9e26-548c3a483dfe">

**Comment by sarithapillai8** [comment]
@carlan1 Could you confirm if any settings are saved for this game or is this an old game? I have updated the code to manage default settings if there are no saved settings. So please check if this is working now.

**Comment by carlan1** [comment]
Can you make the following changes?
1. Check to see that the number of symbols is accurate (I tried to change the number of symbols to 5, but 10 still appeared)
2. Change the setting for whether or not to show the mapping table to "during"
3. At the start, please make the text with instructions as a separate dialog. At the bottom of the dialog, show the start button. 
4. In the instructions, for the "before game" condition, please make the text with "In this game mode, try to memorize the key. Once you press start, it will disappear!" appear in bold. Or some other way to make it more eye catching and noticeable

**Comment by sarithapillai8** [comment]
@carlan1 We will be updating these changes soon.

**Comment by sarithapillai8** [comment]
@carlan1 Please review the changes updated in dashboard-staging. For the 'before' game condition, the popup is with an ok button and this text "In this game mode, try to memorize the key. Once you press start, it will disappear!"' with a start button added above the game. Could you please let me know if any change required?

**Comment by carlan1** [comment]
Looks good. Thank you
